export enum Icons {
    FOLDER = 'folder.ico',
    WINDOWS = 'windows.ico',
    TEXT_DOCUMENT = 'text_document.ico',
    MY_COMPUTER = 'my_computer.ico',
    PROGRAM = 'program.ico',
    SHORTCUT = 'shortcut.ico',
    TURNOFF_COMPUTER = 'turnoff_computer.ico',
    EMPTY_RECYCLE_BIN = 'empty_recycle_bin.ico',
    PAINT = 'paint.ico',
    DRIVE = 'drive.ico',
    OPENED_FOLDER = 'opened_folder.ico',
    FIND_FILE = "find_file.ico",
    SHUT_DOWN = "shut_down.ico",
    SETTINGS = "settings.ico",
    HELP_BOOK = "help_book.ico",
    PROGRAM_WAIT = "program_wait.ico",
    DOCUMENTS_FOLDER = "documents_folder.ico",
    WEB_DOCUMENTS = "web_documents.ico",
    PROGRAMS_FOLDER = "programs_folder.ico",
    CONTROL_PANEL = "control_panel.ico",
    COMPUTER_WITH_PROGRAMS = "computer_with_programs.ico",
}